/* 
          __             __                
    _____/ /_____ ______/ /________________
   / ___/ __/ __ `/ ___/ __/ ___/ ___/ ___/
  (__  ) /_/ /_/ / /  / /_/ /__(__  |__  ) 
 /____/\__/\__,_/_/   \__/\___/____/____/  v0.0.1 

*/

import { generatePalettes } from "./⚡/generatePalettes.js";

// Add or modify colors as you like. Custom properties names will match definitions.
// Defined color will be accesible as var(--your-color).
// Ex. var(--accent);

// Autogenerated palettes will be accesible from 100 to 900.
// Ex. var(--accent-100);

// All colors and palettes will generate an HSL custom property helper for opacities.
// Ex. hsl(var(--accent-hsl), 0.5);
// Ex. hsl(var(--accent-100-hsl), 0.5);

const colors = {
  base: "#fafafa",
  accent: "#FFD55E",
  alt: "#041A40",
  info: "#1E4BCA",
  success: "#4BB543",
  warning: "#FF7900",
  error: "#CB0B44",
}

generatePalettes(colors);